# Generated by Django 3.1.7 on 2021-04-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('subject', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('username', models.CharField(max_length=250)),
                ('per_hour', models.CharField(max_length=250)),
                ('Age', models.CharField(max_length=250)),
            ],
        ),
    ]
