# Generated by Django 3.1.7 on 2021-04-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.CharField(default=2, max_length=250),
            preserve_default=False,
        ),
    ]
