# Generated by Django 3.1.7 on 2021-04-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_register_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
