# Generated by Django 3.1.7 on 2021-04-21 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_messagetoteacher_studentmsg'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(max_length=250)),
                ('file', models.FileField(upload_to='files')),
                ('student', models.ManyToManyField(related_name='student_file', to='classroom.Student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_file', to='classroom.teacher')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmitFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('submit', models.FileField(upload_to='Submission')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_submit', to='classroom.student')),
                ('submitted_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_for_file', to='classroom.classfile')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_submit', to='classroom.teacher')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
