# Generated by Django 3.1.7 on 2021-04-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_classfile_submitfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='message_teach_admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=1000)),
            ],
        ),
    ]
