# Generated by Django 3.1.7 on 2021-04-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_message_teach_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='message_student_admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=1000)),
            ],
        ),
    ]
