# Generated by Django 3.1.7 on 2021-05-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_message_student_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Change_Salary_Demand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeacherName', models.TextField(max_length=1000)),
                ('message', models.TextField(max_length=1000)),
            ],
        ),
    ]
