pipeline {
    agent {
        docker {
            image 'python:3.8.0'

        }
    }
    stages {
        stage('build') {
            steps {
                withEnv(["HOME=${env.WORKSPACE}"]) {
                    sh "python -m pip install -r lemudim1/requirements.txt --user"
                }
            }
        }


    }
}